# Generated by Django 3.2.15 on 2022-11-07 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.TextField(verbose_name='教室名')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.TextField(verbose_name='曜日')),
                ('period_of_time', models.TextField(verbose_name='時限')),
                ('className', models.TextField(verbose_name='授業名')),
                ('term', models.TextField(verbose_name='ターム')),
                ('class_number', models.TextField(verbose_name='教室名')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '空き教室',
                'verbose_name_plural': '空き教室リスト',
                'db_table': 'akikyoushitu',
            },
        ),
        migrations.CreateModel(
            name='Friday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金')], max_length=50, verbose_name='曜日')),
                ('pot', models.CharField(choices=[('0', '1限'), ('1', '2限'), ('2', '3限'), ('3', '4限'), ('4', '5限'), ('5', '6限')], max_length=50, verbose_name='時限')),
                ('className', models.TextField(blank=True, default='-----', null=True, verbose_name='授業名')),
                ('class_number', models.TextField(blank=True, default='-----', null=True, verbose_name='教室名')),
                ('profName', models.TextField(blank=True, default='-----', null=True, verbose_name='教授名')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.TextField()),
                ('className', models.TextField()),
                ('term', models.TextField()),
                ('day_of_week', models.TextField()),
                ('period_of_time', models.TextField()),
                ('teacher_name', models.TextField()),
                ('gakka', models.TextField()),
                ('syllabusinfo', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thursday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField(verbose_name='授業名')),
                ('kyoin_name', models.TextField(verbose_name='教員名')),
                ('juko_year', models.TextField(blank=True, null=True, verbose_name='受講年度')),
                ('tor', models.CharField(choices=[('0', 'テスト'), ('1', 'レポート'), ('2', 'なし')], max_length=50, verbose_name='テスト or レポート')),
                ('lms', models.CharField(choices=[('0', 'moodle'), ('1', 'Google Classroom'), ('2', 'ポートフォリオ'), ('3', 'その他'), ('4', 'なし')], max_length=50, verbose_name='学習管理システム')),
                ('aa', models.CharField(choices=[('0', 'とても多い'), ('1', '多い'), ('2', '普通'), ('3', '少ない'), ('4', 'ほとんどない'), ('5', 'ない')], max_length=50, verbose_name='課題量')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gakka', models.CharField(max_length=10)),
                ('gakunen', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
