# Generated by Django 3.2.15 on 2022-11-10 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tsuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='author_jikanwari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
    ]
