# Generated by Django 3.2.15 on 2022-12-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1',
            name='className',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='t1',
            name='class_number',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='t1',
            name='profName',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教授名'),
        ),
        migrations.AlterField(
            model_name='t2',
            name='className',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='t2',
            name='class_number',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='t2',
            name='profName',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教授名'),
        ),
        migrations.AlterField(
            model_name='t3',
            name='className',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='t3',
            name='class_number',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='t3',
            name='profName',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教授名'),
        ),
        migrations.AlterField(
            model_name='t4',
            name='className',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='t4',
            name='class_number',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='t4',
            name='profName',
            field=models.TextField(blank=True, default='--', null=True, verbose_name='教授名'),
        ),
    ]
