# Generated by Django 3.2.15 on 2022-11-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0002_alter_monday1_author_jikanwari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='author_jikanwari',
            field=models.TextField(blank=True, null=True, verbose_name='作成者'),
        ),
    ]
