# Generated by Django 3.2.15 on 2022-09-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0002_kyoshitsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyoshitsu',
            name='classID',
            field=models.TextField(),
        ),
    ]
