# Generated by Django 3.2.15 on 2023-01-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0002_auto_20221221_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='allclass',
            options={'verbose_name': 'Allclass', 'verbose_name_plural': 'Allclass'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classroom'},
        ),
        migrations.AlterModelOptions(
            name='syllabuscomment',
            options={'verbose_name': 'SyllabusComment', 'verbose_name_plural': 'SyllabusComment'},
        ),
        migrations.AlterModelOptions(
            name='t1',
            options={'verbose_name': 'T1', 'verbose_name_plural': 'T1'},
        ),
        migrations.AlterModelOptions(
            name='t2',
            options={'verbose_name': 'T2', 'verbose_name_plural': 'T2'},
        ),
        migrations.AlterModelOptions(
            name='t3',
            options={'verbose_name': 'T3', 'verbose_name_plural': 'T3'},
        ),
        migrations.AlterModelOptions(
            name='t4',
            options={'verbose_name': 'T4', 'verbose_name_plural': 'T4'},
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='allclass',
            table='Allclass',
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='Classroom',
        ),
        migrations.AlterModelTable(
            name='syllabuscomment',
            table='SyllabusComment',
        ),
        migrations.AlterModelTable(
            name='t1',
            table='T1',
        ),
        migrations.AlterModelTable(
            name='t2',
            table='T2',
        ),
        migrations.AlterModelTable(
            name='t3',
            table='T3',
        ),
        migrations.AlterModelTable(
            name='t4',
            table='T4',
        ),
    ]
