# Generated by Django 3.2.15 on 2022-11-21 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0003_alter_monday1_author_jikanwari'),
    ]

    operations = [
        migrations.AddField(
            model_name='monday2',
            name='author_jikanwari_2',
            field=models.TextField(blank=True, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='monday2',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monday2',
            name='dow',
            field=models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金')], default=1, max_length=50, verbose_name='曜日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday2',
            name='pot',
            field=models.CharField(choices=[('0', '1限'), ('1', '2限'), ('2', '3限'), ('3', '4限'), ('4', '5限'), ('5', '6限')], default=2, max_length=50, verbose_name='時限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday2',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monday3',
            name='author_jikanwari_3',
            field=models.TextField(blank=True, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='monday3',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monday3',
            name='dow',
            field=models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金')], default=3, max_length=50, verbose_name='曜日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday3',
            name='pot',
            field=models.CharField(choices=[('0', '1限'), ('1', '2限'), ('2', '3限'), ('3', '4限'), ('4', '5限'), ('5', '6限')], default=4, max_length=50, verbose_name='時限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday3',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monday4',
            name='author_jikanwari_4',
            field=models.TextField(blank=True, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='monday4',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monday4',
            name='dow',
            field=models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金')], default=5, max_length=50, verbose_name='曜日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday4',
            name='pot',
            field=models.CharField(choices=[('0', '1限'), ('1', '2限'), ('2', '3限'), ('3', '4限'), ('4', '5限'), ('5', '6限')], default=0, max_length=50, verbose_name='時限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday4',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monday2',
            name='className',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='monday2',
            name='class_number',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='monday2',
            name='profName',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教授名'),
        ),
        migrations.AlterField(
            model_name='monday3',
            name='className',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='monday3',
            name='class_number',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='monday3',
            name='profName',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教授名'),
        ),
        migrations.AlterField(
            model_name='monday4',
            name='className',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='monday4',
            name='class_number',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='monday4',
            name='profName',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教授名'),
        ),
    ]
