# Generated by Django 3.2.15 on 2022-09-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0003_alter_kyoshitsu_classid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kyoshitsu',
            new_name='Classroom',
        ),
    ]
