# Generated by Django 3.2.15 on 2022-10-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0004_rename_kyoshitsu_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Friday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thursday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('class_number', models.TextField()),
                ('profName', models.TextField()),
            ],
        ),
    ]
