# Generated by Django 3.2.15 on 2022-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0004_rename_kyoshitsu_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.TextField()),
                ('class_name', models.TextField()),
                ('term_number', models.TextField()),
                ('day_of_week', models.TextField()),
                ('period_of_time', models.TextField()),
                ('teacher_name', models.TextField()),
                ('eibun', models.TextField()),
                ('kokkan', models.TextField()),
                ('tabunka', models.TextField()),
                ('sugaku', models.TextField()),
                ('johou', models.TextField()),
                ('syllabus_info', models.TextField()),
            ],
        ),
    ]
