# Generated by Django 3.2.15 on 2022-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0005_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='term_number',
            new_name='term_1',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='term_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='term_3',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='term_4',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
