# Generated by Django 3.2.15 on 2022-12-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0005_auto_20221212_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friday1',
        ),
        migrations.DeleteModel(
            name='Friday2',
        ),
        migrations.DeleteModel(
            name='Friday3',
        ),
        migrations.DeleteModel(
            name='Friday4',
        ),
        migrations.DeleteModel(
            name='Friday5',
        ),
        migrations.DeleteModel(
            name='Friday6',
        ),
        migrations.DeleteModel(
            name='Monday5',
        ),
        migrations.DeleteModel(
            name='Monday6',
        ),
        migrations.DeleteModel(
            name='Thursday1',
        ),
        migrations.DeleteModel(
            name='Thursday2',
        ),
        migrations.DeleteModel(
            name='Thursday3',
        ),
        migrations.DeleteModel(
            name='Thursday4',
        ),
        migrations.DeleteModel(
            name='Thursday5',
        ),
        migrations.DeleteModel(
            name='Thursday6',
        ),
        migrations.DeleteModel(
            name='Tuesday1',
        ),
        migrations.DeleteModel(
            name='Tuesday2',
        ),
        migrations.DeleteModel(
            name='Tuesday3',
        ),
        migrations.DeleteModel(
            name='Tuesday4',
        ),
        migrations.DeleteModel(
            name='Tuesday5',
        ),
        migrations.DeleteModel(
            name='Tuesday6',
        ),
        migrations.DeleteModel(
            name='Wednesday1',
        ),
        migrations.DeleteModel(
            name='Wednesday2',
        ),
        migrations.DeleteModel(
            name='Wednesday3',
        ),
        migrations.DeleteModel(
            name='Wednesday4',
        ),
        migrations.DeleteModel(
            name='Wednesday5',
        ),
        migrations.DeleteModel(
            name='Wednesday6',
        ),
    ]
