# Generated by Django 3.2.15 on 2022-12-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0006_auto_20221212_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monday1',
            new_name='T1',
        ),
        migrations.RenameModel(
            old_name='Monday4',
            new_name='T2',
        ),
        migrations.RenameModel(
            old_name='Monday2',
            new_name='T3',
        ),
        migrations.RenameModel(
            old_name='Monday3',
            new_name='T4',
        ),
        migrations.RenameField(
            model_name='t2',
            old_name='author_jikanwari_4',
            new_name='author_jikanwari_2',
        ),
        migrations.RenameField(
            model_name='t3',
            old_name='author_jikanwari_2',
            new_name='author_jikanwari_3',
        ),
        migrations.RenameField(
            model_name='t4',
            old_name='author_jikanwari_3',
            new_name='author_jikanwari_4',
        ),
    ]
