# Generated by Django 3.2.15 on 2022-10-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0005_friday1_friday2_friday3_friday4_friday5_friday6_monday1_monday2_monday3_monday4_monday5_monday6_thur'),
        ('tsuda', '0006_auto_20221002_2049'),
    ]

    operations = [
    ]
