# Generated by Django 3.2.15 on 2022-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0006_auto_20221002_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juko_year', models.TextField()),
                ('test_or_report', models.TextField()),
                ('jugyo_document', models.TextField()),
                ('kadai_ryo', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
