# Generated by Django 3.2.15 on 2022-12-13 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0007_auto_20221213_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
