# Generated by Django 3.2.15 on 2022-10-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0007_merge_20221002_2209'),
        ('tsuda', '0008_syllabuscomment_class_name'),
    ]

    operations = [
    ]
