# Generated by Django 3.2.15 on 2022-10-04 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0009_merge_20221002_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='monday1',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monday1',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
