# Generated by Django 3.2.15 on 2022-10-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0009_merge_20221002_2233'),
        ('tsuda', '0010_auto_20221004_1345'),
    ]

    operations = [
    ]
