# Generated by Django 3.2.15 on 2022-10-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0011_merge_20221004_1638'),
        ('tsuda', '0011_merge_20221004_1645'),
    ]

    operations = [
    ]
