# Generated by Django 3.2.15 on 2022-10-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0012_classroom_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='title',
        ),
    ]
