# Generated by Django 3.2.15 on 2022-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0013_remove_classroom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='monday1',
            name='inquiry_id',
            field=models.IntegerField(default=1, verbose_name='day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monday1',
            name='pic',
            field=models.CharField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金')], default=1, max_length=5, verbose_name='day_of_week'),
            preserve_default=False,
        ),
    ]
