# Generated by Django 3.2.15 on 2022-10-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0014_auto_20221006_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monday1',
            old_name='pic',
            new_name='dow',
        ),
        migrations.RemoveField(
            model_name='monday1',
            name='inquiry_id',
        ),
    ]
