# Generated by Django 3.2.15 on 2022-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0015_auto_20221006_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='monday1',
            name='pot',
            field=models.CharField(choices=[(0, '1限'), (1, '2限'), (2, '3限'), (3, '4限'), (4, '5限'), (5, '6限')], default=1, max_length=5, verbose_name='period_of_time'),
            preserve_default=False,
        ),
    ]
