# Generated by Django 3.2.15 on 2022-10-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0018_auto_20221006_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='dow',
            field=models.CharField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金')], default='', max_length=50, verbose_name='曜日'),
        ),
    ]
