# Generated by Django 3.2.15 on 2022-10-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0022_alter_monday1_dow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='pot',
            field=models.CharField(choices=[('0', '1限'), ('1', '2限'), ('2', '3限'), ('3', '4限'), ('4', '5限'), ('5', '6限')], default='', max_length=50, verbose_name='時限'),
        ),
    ]
