# Generated by Django 3.2.15 on 2022-10-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0024_auto_20221006_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='dow',
            field=models.CharField(choices=[('0', '月'), ('1', '火'), ('2', '水'), ('3', '木'), ('4', '金')], max_length=50, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='monday1',
            name='pot',
            field=models.CharField(choices=[('0', '1限'), ('1', '2限'), ('2', '3限'), ('3', '4限'), ('4', '5限'), ('5', '6限')], max_length=50, verbose_name='period'),
        ),
    ]
