# Generated by Django 3.2.15 on 2022-10-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0026_auto_20221006_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='className',
            field=models.TextField(default='-----', verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='monday1',
            name='class_number',
            field=models.TextField(default='-----', verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='monday1',
            name='profName',
            field=models.TextField(default='-----', verbose_name='教授名'),
        ),
    ]
