# Generated by Django 3.2.15 on 2022-10-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0012_merge_20221004_1719'),
        ('tsuda', '0026_auto_20221006_1541'),
    ]

    operations = [
    ]
