# Generated by Django 3.2.15 on 2022-10-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0027_auto_20221007_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday1',
            name='className',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='monday1',
            name='class_number',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='monday1',
            name='profName',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='教授名'),
        ),
    ]
