# Generated by Django 3.2.15 on 2022-10-08 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0028_auto_20221008_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabuscomment',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='syllabuscomment',
            name='jugyo_document',
        ),
        migrations.RemoveField(
            model_name='syllabuscomment',
            name='kadai_ryo',
        ),
        migrations.RemoveField(
            model_name='syllabuscomment',
            name='test_or_report',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabuscomment',
            name='aa',
            field=models.CharField(choices=[('0', 'とても多い'), ('1', '多い'), ('2', '普通'), ('3', '少ない'), ('4', 'ほとんどない'), ('5', 'ない')], default=1, max_length=50, verbose_name='課題量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabuscomment',
            name='className',
            field=models.TextField(default='-----', verbose_name='授業名'),
        ),
        migrations.AddField(
            model_name='syllabuscomment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='syllabuscomment',
            name='lms',
            field=models.CharField(choices=[('0', 'ムードル'), ('1', 'レポート'), ('2', 'ポートフォリオ'), ('3', 'その他')], default=2, max_length=50, verbose_name='学習管理システム'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabuscomment',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabuscomment',
            name='tor',
            field=models.CharField(choices=[('0', 'テスト'), ('1', 'レポート'), ('2', 'なし')], default=3, max_length=50, verbose_name='テスト or レポート'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabuscomment',
            name='comment',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='syllabuscomment',
            name='juko_year',
            field=models.TextField(blank=True, default='-----', null=True, verbose_name='受講年度'),
        ),
    ]
