# Generated by Django 3.2.15 on 2022-10-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0029_auto_20221008_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='class_name',
            new_name='className',
        ),
    ]
