# Generated by Django 3.2.15 on 2022-10-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0030_rename_class_name_syllabus_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuscomment',
            name='lms',
            field=models.CharField(choices=[('0', 'moodle'), ('1', 'Google Classroom'), ('2', 'ポートフォリオ'), ('3', 'その他'), ('4', 'なし')], max_length=50, verbose_name='学習管理システム'),
        ),
    ]
