# Generated by Django 3.2.15 on 2022-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0031_alter_syllabuscomment_lms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuscomment',
            name='className',
            field=models.TextField(verbose_name='授業名'),
        ),
        migrations.AlterField(
            model_name='syllabuscomment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='syllabuscomment',
            name='juko_year',
            field=models.TextField(blank=True, null=True, verbose_name='受講年度'),
        ),
    ]
