# Generated by Django 3.2.15 on 2022-10-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0032_auto_20221008_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='syllabus_info',
            new_name='syllabusinfo',
        ),
    ]
