# Generated by Django 3.2.15 on 2022-10-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0027_merge_20221006_1609'),
        ('tsuda', '0033_rename_syllabus_info_syllabus_syllabusinfo'),
    ]

    operations = [
    ]
