# Generated by Django 3.2.15 on 2022-10-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0034_merge_20221010_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='eibun',
            new_name='gakka',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='johou',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='kokkan',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='sugaku',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='tabunka',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='term_1',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='term_2',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='term_3',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='term_4',
        ),
    ]
