# Generated by Django 3.2.15 on 2022-10-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0035_auto_20221024_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuscomment',
            name='kyoin_name',
            field=models.TextField(default=1, verbose_name='教員名'),
            preserve_default=False,
        ),
    ]
