# Generated by Django 3.2.15 on 2022-10-26 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0036_syllabuscomment_kyoin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='building_number',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='classID',
            new_name='day_of_week',
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='classroom',
            name='period_of_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='term',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
