# Generated by Django 3.2.15 on 2022-11-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0039_allclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '空き教室', 'verbose_name_plural': '空き教室リスト'},
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='akikyoushitu',
        ),
    ]
