# Generated by Django 3.2.15 on 2022-11-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0041_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='gakka',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='gakunen',
        ),
    ]
