# Generated by Django 3.2.15 on 2022-11-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuda', '0044_auto_20221108_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabuscomment',
            name='author',
        ),
    ]
