# Generated by Django 3.2.15 on 2022-11-08 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tsuda', '0045_remove_syllabuscomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuscomment',
            name='author_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
